# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('WORD', 'Word'), ('PDF', 'PDF')], default='PDF', max_length=2)),
                ('upload', models.FileField(upload_to='uploads/')),
                ('topics', models.CharField(max_length=500)),
            ],
        ),
    ]
